# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rover.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rover.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brover.proto\x12\x05rover\" \n\x0cRoverRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\"\x1a\n\x0bMapResponse\x12\x0b\n\x03map\x18\x01 \x03(\t\"\"\n\x0f\x43ommandResponse\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"+\n\x12MineSerialResponse\x12\x15\n\rserial_number\x18\x01 \x01(\t2\xcd\x01\n\rGroundControl\x12\x33\n\x06GetMap\x12\x13.rover.RoverRequest\x1a\x12.rover.MapResponse\"\x00\x12>\n\x0bGetCommands\x12\x13.rover.RoverRequest\x1a\x16.rover.CommandResponse\"\x00\x30\x01\x12G\n\x13GetMineSerialNumber\x12\x13.rover.RoverRequest\x1a\x19.rover.MineSerialResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rover_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROVERREQUEST']._serialized_start=22
  _globals['_ROVERREQUEST']._serialized_end=54
  _globals['_MAPRESPONSE']._serialized_start=56
  _globals['_MAPRESPONSE']._serialized_end=82
  _globals['_COMMANDRESPONSE']._serialized_start=84
  _globals['_COMMANDRESPONSE']._serialized_end=118
  _globals['_MINESERIALRESPONSE']._serialized_start=120
  _globals['_MINESERIALRESPONSE']._serialized_end=163
  _globals['_GROUNDCONTROL']._serialized_start=166
  _globals['_GROUNDCONTROL']._serialized_end=371
# @@protoc_insertion_point(module_scope)
